// This file is @generated by prost-build.
/// Base parameters common to all market data queries
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BaseMarketParams {
    /// Required: Data source
    #[prost(enumeration = "super::super::data::v1::DataBroker", tag = "1")]
    pub data_broker: i32,
    /// Required: Symbol identifier (e.g., "btc-usdt", "6ez5")
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    /// Required: Year for data retrieval
    #[prost(int32, tag = "3")]
    pub year: i32,
    /// Optional: Exchange name. Defaults to data_broker name if empty.
    #[prost(string, tag = "4")]
    pub exchange: ::prost::alloc::string::String,
    /// Optional: Batch size for streaming. Defaults to 1000. Range: 100-10000.
    #[prost(int32, tag = "5")]
    pub batch_size: i32,
}
/// Aggregation parameters for profile-based data
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfileAggregation {
    /// Aggregation timeframe (e.g., "5m", "1h", "1d", "1w")
    /// Defaults to "1m" if not specified.
    #[prost(string, tag = "1")]
    pub time_frame: ::prost::alloc::string::String,
    /// Price bin size in quote currency (e.g., "1.0", "0.01", "0.00005")
    /// Defaults to finest available granularity if not specified.
    #[prost(string, tag = "2")]
    pub price_bin: ::prost::alloc::string::String,
}
/// Standard batch metadata
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchMetadata {
    /// Sequence number for this batch (starts at 0)
    #[prost(int64, tag = "1")]
    pub sequence: i64,
    /// True if this is the final batch
    #[prost(bool, tag = "2")]
    pub is_final: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TradesSpotRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradesSpotResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::TradesSpotBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OhlcvSpotRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
    /// Timeframe period (e.g., "1m", "5m", "1h", "1d")
    /// Defaults to "1m" if not specified.
    #[prost(string, tag = "2")]
    pub period: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OhlcvSpotResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::OhlcvSpotBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OhlcvFutureRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
    /// Timeframe period (e.g., "1m", "5m", "1h", "1d")
    /// Defaults to "1m" if not specified.
    #[prost(string, tag = "2")]
    pub period: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OhlcvFutureResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::OhlcvFutureBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TpoSpotRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
    /// Optional: Aggregation parameters
    #[prost(message, optional, tag = "2")]
    pub aggregation: ::core::option::Option<ProfileAggregation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TpoSpotResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::TpoSpotBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TpoFutureRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
    /// Optional: Aggregation parameters
    #[prost(message, optional, tag = "2")]
    pub aggregation: ::core::option::Option<ProfileAggregation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TpoFutureResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::TpoFutureBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VolumeProfileSpotRequest {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<BaseMarketParams>,
    /// Optional: Aggregation parameters
    #[prost(message, optional, tag = "2")]
    pub aggregation: ::core::option::Option<ProfileAggregation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VolumeProfileSpotResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::VolumeProfileSpotBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EconomicCalendarRequest {
    /// Required: Data source
    #[prost(enumeration = "super::super::data::v1::DataBroker", tag = "1")]
    pub data_broker: i32,
    /// Required: Year for data retrieval
    #[prost(int32, tag = "2")]
    pub year: i32,
    /// Optional: Filter by data source (e.g., "investingcom", "fred")
    #[prost(string, tag = "3")]
    pub data_source: ::prost::alloc::string::String,
    /// Optional: Filter by country using an ISO 3166-1 alpha-2 uppercase code (e.g., "AU", "US"). The non-standard code "EZ" is supported to indicate the Euro Zone.
    #[prost(string, tag = "4")]
    pub country_code: ::prost::alloc::string::String,
    /// Optional: Filter by economic category.
    #[prost(enumeration = "EconomicCategory", tag = "5")]
    pub category: i32,
    /// Optional: Filter by importance
    #[prost(enumeration = "EconomicImportance", tag = "6")]
    pub importance: i32,
    /// Optional: Batch size. Defaults to 1000.
    #[prost(int32, tag = "7")]
    pub batch_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EconomicCalendarResponse {
    #[prost(message, optional, tag = "1")]
    pub batch: ::core::option::Option<super::super::data::v1::EconomicCalendarBatch>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<BatchMetadata>,
}
/// EconomicCategory identifies the economic classification of calendar events.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EconomicCategory {
    /// Default/unknown category.
    Unspecified = 0,
    /// Employment-related indicators.
    Employment = 1,
    /// Economic activity indicators.
    EconomicActivity = 2,
    /// Inflation-related indicators.
    Inflation = 3,
    /// Credit and lending indicators.
    Credit = 4,
    /// Central bank policy and actions.
    CentralBanks = 5,
    /// Consumer and business confidence indicators.
    ConfidenceIndex = 6,
    /// Balance of payments or trade balance indicators.
    Balance = 7,
    /// Bond market–related indicators.
    Bonds = 8,
}
impl EconomicCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ECONOMIC_CATEGORY_UNSPECIFIED",
            Self::Employment => "ECONOMIC_CATEGORY_EMPLOYMENT",
            Self::EconomicActivity => "ECONOMIC_CATEGORY_ECONOMIC_ACTIVITY",
            Self::Inflation => "ECONOMIC_CATEGORY_INFLATION",
            Self::Credit => "ECONOMIC_CATEGORY_CREDIT",
            Self::CentralBanks => "ECONOMIC_CATEGORY_CENTRAL_BANKS",
            Self::ConfidenceIndex => "ECONOMIC_CATEGORY_CONFIDENCE_INDEX",
            Self::Balance => "ECONOMIC_CATEGORY_BALANCE",
            Self::Bonds => "ECONOMIC_CATEGORY_BONDS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ECONOMIC_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "ECONOMIC_CATEGORY_EMPLOYMENT" => Some(Self::Employment),
            "ECONOMIC_CATEGORY_ECONOMIC_ACTIVITY" => Some(Self::EconomicActivity),
            "ECONOMIC_CATEGORY_INFLATION" => Some(Self::Inflation),
            "ECONOMIC_CATEGORY_CREDIT" => Some(Self::Credit),
            "ECONOMIC_CATEGORY_CENTRAL_BANKS" => Some(Self::CentralBanks),
            "ECONOMIC_CATEGORY_CONFIDENCE_INDEX" => Some(Self::ConfidenceIndex),
            "ECONOMIC_CATEGORY_BALANCE" => Some(Self::Balance),
            "ECONOMIC_CATEGORY_BONDS" => Some(Self::Bonds),
            _ => None,
        }
    }
}
/// EconomicImportance represents the potential market volatility associated with an event.
/// This corresponds directly to the "bull head" rating on Investing.com.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EconomicImportance {
    /// Default value (0). Treated as "Any" or "All Importances" in filters.
    Unspecified = 0,
    /// Low volatility expected. Typically routine reports with minor market impact.
    /// (1 Bull)
    Low = 1,
    /// Moderate volatility expected. Can move markets if significantly off-consensus.
    /// (2 Bulls)
    Moderate = 2,
    /// High volatility expected. Major market movers (e.g., NFP, CPI, Rate Decisions).
    /// (3 Bulls)
    High = 3,
}
impl EconomicImportance {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ECONOMIC_IMPORTANCE_UNSPECIFIED",
            Self::Low => "ECONOMIC_IMPORTANCE_LOW",
            Self::Moderate => "ECONOMIC_IMPORTANCE_MODERATE",
            Self::High => "ECONOMIC_IMPORTANCE_HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ECONOMIC_IMPORTANCE_UNSPECIFIED" => Some(Self::Unspecified),
            "ECONOMIC_IMPORTANCE_LOW" => Some(Self::Low),
            "ECONOMIC_IMPORTANCE_MODERATE" => Some(Self::Moderate),
            "ECONOMIC_IMPORTANCE_HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod exporter_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Market data export service.
    #[derive(Debug, Clone)]
    pub struct ExporterServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ExporterServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ExporterServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ExporterServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ExporterServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stream trade-level spot market data
        pub async fn trades_spot(
            &mut self,
            request: impl tonic::IntoRequest<super::TradesSpotRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TradesSpotResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/TradesSpot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "TradesSpot",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream OHLCV data for spot markets
        pub async fn ohlcv_spot(
            &mut self,
            request: impl tonic::IntoRequest<super::OhlcvSpotRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OhlcvSpotResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/OhlcvSpot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "OhlcvSpot",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream OHLCV data for futures markets
        pub async fn ohlcv_future(
            &mut self,
            request: impl tonic::IntoRequest<super::OhlcvFutureRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OhlcvFutureResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/OhlcvFuture",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "OhlcvFuture",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream TPO data for spot markets
        pub async fn tpo_spot(
            &mut self,
            request: impl tonic::IntoRequest<super::TpoSpotRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TpoSpotResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/TpoSpot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("chapaty.bq_exporter.v1.ExporterService", "TpoSpot"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream TPO data for futures markets
        pub async fn tpo_future(
            &mut self,
            request: impl tonic::IntoRequest<super::TpoFutureRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TpoFutureResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/TpoFuture",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "TpoFuture",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream volume profile data for spot markets
        pub async fn volume_profile_spot(
            &mut self,
            request: impl tonic::IntoRequest<super::VolumeProfileSpotRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::VolumeProfileSpotResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/VolumeProfileSpot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "VolumeProfileSpot",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream economic calendar events
        pub async fn economic_calendar(
            &mut self,
            request: impl tonic::IntoRequest<super::EconomicCalendarRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::EconomicCalendarResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/chapaty.bq_exporter.v1.ExporterService/EconomicCalendar",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "chapaty.bq_exporter.v1.ExporterService",
                        "EconomicCalendar",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
