use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::cmp::{Ordering, Reverse};
use std::collections::BinaryHeap;

use crate::data::view::MarketView;
use crate::error::SystemError;
use crate::{
    data::{domain::Price, episode::Episode},
    error::ChapatyResult,
    gym::flow::{
        domain::RfqId,
        state::{Open, Rfq},
    },
    sim::{cursor_group::CursorGroup, data::SimulationData},
};

// ====================================================================================================
// 1. The Scheduler (Discrete Event Engine)
// ====================================================================================================

/// The central timekeeper for the Flow Trading Environment.
///
/// It synchronizes two disparate time sources:
/// 1. **Exogenous Market Data:** Historical ticks/candles from the `CursorGroup`.
/// 2. **Endogenous Synthetic Events:** RfQs, client replies, and timeouts generated by the simulation.
///
/// This ensures strictly causal ordering.
#[derive(Clone, Debug)]
pub struct Scheduler {
    /// The iterator over the historical market data feed.
    cursor: CursorGroup,

    /// The timestamp of the previous step (useful for calculating dt or debugging monotonicity).
    previous_ts: Option<DateTime<Utc>>,

    /// The current global simulation time.
    current_ts: DateTime<Utc>,
}

/// The result of a single simulation tick.
/// Instructions the `Env` on how to proceed with the state transition.
pub enum ScheduledStep {
    /// **Time Advanced (Market Data).**
    /// The market has moved forward. The Env should check if this volatility/volume
    /// triggers the Generator to produce new RfQs.
    Market { timestamp: DateTime<Utc> },

    /// **Action Required (Synthetic Event).**
    /// An internal event (e.g., Client Reply, Expiration) has popped from the priority queue.
    /// The Env must update the Ledger/State.
    Event(ScheduledEvent),
}

impl Scheduler {
    pub fn new(cursor: CursorGroup) -> Self {
        let ts = cursor.current_ts();
        Self {
            cursor,
            previous_ts: None,
            current_ts: ts,
        }
    }

    pub fn current_ts(&self) -> DateTime<Utc> {
        self.current_ts
    }

    /// Returns a view of the market data at the current simulation time.
    pub fn market_view<'a, 'env>(
        &'a self,
        sim_data: &'env SimulationData,
    ) -> ChapatyResult<MarketView<'env>> {
        MarketView::new(sim_data, &self.cursor)
    }

    pub fn reset(&mut self, sim_data: &SimulationData) {
        self.cursor.reset(sim_data);
        self.previous_ts = None;
        self.current_ts = self.cursor.current_ts();
    }

    pub fn advance_to_next_episode(
        &mut self,
        sim_data: &SimulationData,
        current_ep: Episode,
    ) -> ChapatyResult<Option<Episode>> {
        self.cursor.advance_to_next_episode(sim_data, current_ep)
    }

    pub fn is_end_of_data(
        &self,
        sim_data: &SimulationData,
        queue: &BinaryHeap<Reverse<ScheduledEvent>>,
    ) -> bool {
        self.cursor.is_end_of_data(sim_data) && queue.is_empty()
    }

    /// Determines the next state transition by comparing the timestamp of the next
    /// market tick against the next synthetic event in the priority queue.
    pub fn step(
        &mut self,
        sim_data: &SimulationData,
        ep: &Episode,
        queue: &mut BinaryHeap<Reverse<ScheduledEvent>>,
    ) -> ChapatyResult<Option<ScheduledStep>> {
        let t_market = self.cursor.peek(sim_data);
        let t_queue = queue.peek().map(|e| e.0.timestamp);

        match (t_market, t_queue) {
            (Some(tm), Some(tq)) => {
                if tq <= tm {
                    // CASE A: Synthetic Event is earlier (or simultaneous).
                    // We consume the event from the queue to maintain causality.
                    let event_wrapper = queue.pop().expect("Peeked item must exist");
                    let event = event_wrapper.0;

                    self.update_time(event.timestamp)?;
                    Ok(Some(ScheduledStep::Event(event)))
                } else {
                    // CASE B: Market Data is earlier.
                    // We advance the market cursor.
                    self.cursor.step(sim_data, ep)?;
                    self.update_time(tm);
                    Ok(Some(ScheduledStep::Market { timestamp: tm }))
                }
            }
            (Some(tm), None) => {
                // CASE C: Only Market Data available (Queue empty).
                self.cursor.step(sim_data, ep)?;
                self.update_time(tm)?;
                Ok(Some(ScheduledStep::Market { timestamp: tm }))
            }
            (None, Some(_)) => {
                // CASE D: Market Data exhausted, but events remain (e.g., Settlement/Clearing).
                let event_wrapper = queue.pop().expect("Peeked item must exist");
                let event = event_wrapper.0;

                self.update_time(event.timestamp)?;
                Ok(Some(ScheduledStep::Event(event)))
            }
            (None, None) => {
                // CASE E: End of Simulation.
                Ok(None)
            }
        }
    }

    /// Internal helper to update the master clock and ensure monotonicity.
    fn update_time(&mut self, new_ts: DateTime<Utc>) -> ChapatyResult<()> {
        // Strict Monotonicity Check: t_{n+1} >= t_n
        // In a Discrete Event Simulation, time must be non-decreasing.
        if new_ts < self.current_ts {
            let msg = format!(
                "Monotonicity Violation: new_ts ({:?}) < current_ts ({:?}). \
                    Time cannot flow backwards. \
                    Possible causes: \
                        1) Unsorted Market Data (Cursor), \
                        2) Unsorted Priority Queue (Reverse wrapper missing?), \
                        3) Synthetic Event generated in the past, \
                        4) Other. \
                Invariant violation: It must always be guaranteed cursor.current_ts <= scheduler.current_ts",
                new_ts, self.current_ts
            );
            tracing::error!(msg);
            return Err(SystemError::InvariantViolation(msg).into());
        }

        self.previous_ts = Some(self.current_ts);
        self.current_ts = new_ts;

        Ok(())
    }
}

// ====================================================================================================
// 2. Events & Payloads
// ====================================================================================================

/// Represents the specific type of business event occurring in the flow lifecycle.
#[derive(Debug, Clone)]
pub enum RfqEvent {
    /// **Inbound Request:** The Generator has produced a new client interest.
    /// The agent must now decide whether to quote.
    NewRequest(Rfq<Open>),

    /// **Client Feedback:** The probabilistic model has made a decision on the agent's quote.
    CustomerReply {
        rfq_id: RfqId,
        decision: CustomerDecision,
    },

    /// **Timeout:** The RfQ's `time_to_live` has elapsed without a finalized deal.
    Expired {
        rfq_id: RfqId,
    },

    WakeUp,
}

/// The outcome of the client's decision-making process.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum CustomerDecision {
    /// Client accepted the price. Trade is booked.
    Accept,

    /// Client rejected the price (too far from fair value).
    Reject,

    /// Client proposes a new price (Negotiation).
    Counter(Price),
}

impl CustomerDecision {
    pub fn is_accept(&self) -> bool {
        matches!(self, CustomerDecision::Accept)
    }

    pub fn is_reject(&self) -> bool {
        matches!(self, CustomerDecision::Reject)
    }

    pub fn is_counter(&self) -> bool {
        matches!(self, CustomerDecision::Counter(_))
    }

    pub fn counter_price(&self) -> Option<Price> {
        match self {
            CustomerDecision::Counter(price) => Some(*price),
            _ => None,
        }
    }

    pub fn requires_agent_reply(&self) -> bool {
        self.is_accept() || self.is_counter()
    }
}

/// A wrapper for events that need to be scheduled in the future.
///
/// Implements `Ord` based on `timestamp` to function within a Priority Queue.
#[derive(Clone, Debug)]
pub struct ScheduledEvent {
    pub timestamp: DateTime<Utc>,
    pub event_type: RfqEvent,
}

impl PartialEq for ScheduledEvent {
    fn eq(&self, other: &Self) -> bool {
        self.timestamp == other.timestamp
    }
}

impl Eq for ScheduledEvent {}

impl PartialOrd for ScheduledEvent {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for ScheduledEvent {
    fn cmp(&self, other: &Self) -> Ordering {
        self.timestamp.cmp(&other.timestamp)
    }
}

#[cfg(test)]
mod tests {
    // TODO use super::*;

    #[test]
    fn invariant_test() {
        assert!(false, "Teste die Invariante")
    }
}
